
export const getPrescriptionTemplate = (data) => {
   const {
      hospitalName,
      hospitalAddress,
      hospitalPhone,
      hospitalEmail,
      patientName,
      age,
      gender,
      weight,
      height,
      date,
      mrn,
      symptoms,
      diagnosis,
      medicines,
      dietAdvice,
      tests,
      followUp,
      avoid,
      doctorName,
      doctorQual,
      doctorSigText,
      qrCodeUrl, // Optional
      showVitals,
      doctorSig,
      doctorSpecialization
   } = data;

   // Inline CSS based on demo.html
   // Note: html2canvas requires specific handling for some styles. 
   // We use standard inline styles.

   return `
    <div style="font-family: 'Inter', system-ui, sans-serif; background: #fff; color: #0f172a; width: 800px; padding: 0; margin: 0; box-sizing: border-box; position: relative; overflow: hidden;">
      
      <!-- Watermark -->
      <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); font-size: 50px; color: rgba(0, 0, 0, 0.05); font-weight: 900; white-space: nowrap; pointer-events: none; z-index: 0;">
        ${hospitalName || 'Hospital'}
      </div>

      <div style="position: relative; z-index: 1; border: 2px solid #e6eef9; padding: 0;">
        
        <!-- HEADER -->
        <div style="padding: 24px; border-bottom: 2px solid #e6eef9; display: flex; justify-content: space-between; align-items: flex-start; background: #fff;">
          <div style="display: flex; gap: 20px; align-items: center;">
             <!-- Logo -->
            <div style="width: 80px; height: 80px; display: flex; align-items: center; justify-content: center;">
              <img src="/assets/image-removebg-preview.png" alt="Logo" style="width: 100%; height: 100%; object-fit: contain;" />
            </div>
            <div>
              <h1 style="margin: 0; color: #2b7bd3; font-size: 26px; font-weight: 700; letter-spacing: 0.5px;">PRESCRIPTION</h1>
              <div style="font-size: 12px; color: #6b7280; margin-top: 4px;">Generated by MSecureChain</div>
              <div style="font-size: 13px; color: #374151; margin-top: 12px; line-height: 1.4;">
                <strong style="color: #0f172a; font-size: 14px;">${hospitalName || 'Sun Rise Hospital'}</strong><br>
                ${hospitalAddress || 'Kadapa 515001, Andhra Pradesh'}<br>
                Phone: ${hospitalPhone || '+91 9876543210'}
              </div>
            </div>
          </div>

          <div style="text-align: right; font-size: 13px; color: #374151;">
             <table style="width: 100%; border-collapse: collapse;">
                <tr>
                   <td style="font-weight: 600; padding-right: 8px; text-align: right; color: #0f172a;">Date:</td>
                   <td style="text-align: left;">${date}</td>
                </tr>
                <tr>
                   <td style="font-weight: 600; padding-right: 8px; text-align: right; color: #0f172a;">MRN:</td>
                   <td style="text-align: left;">${mrn || 'N/A'}</td>
                </tr>
             </table>
          </div>
        </div>

        <!-- MAIN CONTENT -->
        <div style="padding: 24px;">

           <!-- PATIENT & DOCTOR CARD -->
         <div style="padding: 0 0 24px 0;">
            <div style="background: rgba(47, 85, 151, 0.03); border: 1px solid #e6eef9; padding: 24px; border-radius: 12px; display: flex; justify-content: space-between; gap: 40px; margin-bottom: 24px;">
               
               <!-- Left Column: Patient Info -->
               <div style="font-size: 14px; color: #334155; line-height: 1.8; flex: 1;">
                  <div style="display: grid; grid-template-columns: 100px 1fr; gap: 8px; margin-bottom: 4px;">
                     <strong style="color: #0f172a;">Patient:</strong> 
                     <span style="font-weight: 600; color: #1e293b;">${patientName}</span>
                  </div>
                  <div style="display: grid; grid-template-columns: 100px 1fr; gap: 8px; margin-bottom: 4px;">
                     <strong style="color: #0f172a;">Age/Gender:</strong> 
                     <span>${age || '-'} / ${gender || '-'}</span>
                  </div>
                  ${showVitals && weight && weight !== '-' ? `
                  <div style="display: grid; grid-template-columns: 100px 1fr; gap: 8px; margin-bottom: 4px;">
                     <strong style="color: #0f172a;">Weight:</strong> 
                     <span>${weight} kg</span>
                  </div>` : ''}
                  ${showVitals && height && height !== '-' ? `
                  <div style="display: grid; grid-template-columns: 100px 1fr; gap: 8px; margin-bottom: 4px;">
                     <strong style="color: #0f172a;">Height:</strong> 
                     <span>${height} cm</span>
                  </div>
                  ` : ''}
                  <div style="display: grid; grid-template-columns: 100px 1fr; gap: 8px; margin-top: 8px;">
                     <strong style="color: #0f172a;">Reason:</strong> 
                     <span>${symptoms || 'N/A'}</span>
                  </div>
               </div>

               <!-- Right Column: Doctor Info -->
               <div style="font-size: 14px; color: #334155; line-height: 1.8; flex: 1; text-align: left; border-left: 1px solid #e2e8f0; padding-left: 32px;">
                  <div style="display: grid; grid-template-columns: 100px 1fr; gap: 8px; margin-bottom: 4px;">
                     <strong style="color: #0f172a;">Physician:</strong> 
                     <span style="font-weight: 600; color: #1e293b;">${doctorName || 'Dr. T. Anand Kumar'}</span>
                  </div>
                  <div style="display: grid; grid-template-columns: 100px 1fr; gap: 8px; margin-bottom: 4px;">
                     <strong style="color: #0f172a;">Qualification:</strong> 
                     <span>${doctorQual || 'MBBS, MD'}</span>
                  </div>
                   <div style="display: grid; grid-template-columns: 100px 1fr; gap: 8px; margin-top: 8px;">
                      <strong style="color: #0f172a;">Specialist:</strong> 
                      <span>${doctorSpecialization || 'General Physician'}</span>
                   </div>
               </div>
            </div>

          <!-- MEDICINES -->
          <div style="margin-bottom: 24px;">
            <h3 style="color: #2b7bd3; font-size: 16px; font-weight: 700; border-bottom: 1px solid #e6eef9; padding-bottom: 8px; margin: 0 0 12px 0;">MEDICINES</h3>
            <ul style="list-style: none; padding: 0; margin: 0;">
              ${medicines.length > 0
         ? medicines.map(m => `
                  <li style="padding: 10px 0; border-bottom: 1px dashed #e6eef9; font-size: 14px; color: #1e293b; display: flex; align-items: flex-start; gap: 8px;">
                    <span style="color: #2b7bd3; font-weight: bold;">•</span>
                    <span>${m}</span>
                  </li>`).join('')
         : '<li style="padding: 10px 0; color: #94a3b8; font-style: italic;">No medicines prescribed</li>'
      }
            </ul>
          </div>

          <!-- SPLIT TESTS & DIET -->
          <div style="display: flex; gap: 32px; margin-bottom: 24px;">
             <div style="flex: 1;">
                <h3 style="color: #2b7bd3; font-size: 15px; font-weight: 700; margin: 0 0 10px 0;">DIET ADVICE</h3>
                <ul style="padding-left: 16px; margin: 0; font-size: 14px; color: #475569; line-height: 1.6;">
                   ${dietAdvice.length > 0 ? dietAdvice.map(d => `<li>${d}</li>`).join('') : '<li>None</li>'}
                </ul>
             </div>
             <div style="flex: 1;">
                <h3 style="color: #2b7bd3; font-size: 15px; font-weight: 700; margin: 0 0 10px 0;">TESTS</h3>
                <ul style="padding-left: 16px; margin: 0; font-size: 14px; color: #475569; line-height: 1.6;">
                   ${tests.length > 0 ? tests.map(t => `<li>${t}</li>`).join('') : '<li>None</li>'}
                </ul>
             </div>
          </div>

          <!-- FOLLOW UP & AVOID -->
          <div style="padding: 16px; border-radius: 8px; margin-bottom: 24px;">
             <div style="margin-bottom: 12px;">
                <strong style="color: #2b7bd3; font-size: 14px;">FOLLOW UP:</strong>
                <span style="font-size: 14px; color: #334155; margin-left: 8px;">${followUp || 'As required'}</span>
             </div>
             <div>
                <strong style="color: #2b7bd3; font-size: 14px;">AVOID:</strong>
                <span style="font-size: 14px; color: #334155; margin-left: 8px;">
                   ${avoid.length > 0 ? avoid.join(', ') : 'None'}
                </span>
             </div>
          </div>

          <!-- SIGNATURE -->
          <div style="display: flex; justify-content: flex-end; margin-top: 32px;">
             <div style="text-align: center;">
                <div style="height: 60px; margin-bottom: 8px; display: flex; align-items: center; justify-content: center;">
                   ${doctorSig
         ? `<img src="${doctorSig}" style="height: 100%; max-width: 150px; object-fit: contain;" />`
         : (doctorSigText
            ? `<span style="font-family: 'Brush Script MT', cursive; font-size: 24px; color: #1e293b;">${doctorSigText}</span>`
            : '')
      }
                </div>
                <div style="border-top: 1px solid #94a3b8; padding-top: 4px; font-size: 14px; font-weight: 600; color: #0f172a;">
                   
                </div>
                <div style="font-size: 11px; color: #6b7280;">(Doctor's Signature)</div>
             </div>
          </div>

        </div>

        <!-- FOOTER -->
        <div style="background: #f8fafc; border-top: 1px dashed #cbd5e1; padding: 16px 24px; display: flex; justify-content: space-between; align-items: center; font-size: 12px; color: #64748b;">
           <div>
              <div>Generated on: ${date}</div>
              <div style="margin-top: 2px;">www.mscurechain.com</div>
           </div>
           
            <div style="text-align: right;">
               <div>Electronically generated prescription</div>
               <div style="margin-top: 2px; color: #2b7bd3; font-weight: 500;">Safe & Secure</div>
            </div>
        </div>

      </div>
    </div>
  `;
};
